version: '3.3'

services:
  app:
    image: bb-messaging-api-image
    ports:
      - 3333:3001
    networks:
      - web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./mockoon-messaging.json:/mockoon-messaging.json

networks:
  web:
    driver: bridge